#!/bin/bash

set -v
set -e
set -o pipefail

DEFAULT_PORT_BACKEND_SERVER=30050
DEFAULT_PORT_FRONTEND_DASHBOARD=30091

PORT_BACKEND_SERVER=${PORT_BACKEND_SERVER:-${DEFAULT_PORT_BACKEND_SERVER}}
PORT_FRONTEND_DASHBOARD=${PORT_FRONTEND_DASHBOARD:-${DEFAULT_PORT_FRONTEND_DASHBOARD}}

cd /usr/share/nginx/html/static

TARGET_FILE="app.*.js"

cp app.template ${TARGET_FILE}

sed -i "s/:${DEFAULT_PORT_BACKEND_SERVER}/:${PORT_BACKEND_SERVER}/g" ${TARGET_FILE}
sed -i "s/:${DEFAULT_PORT_FRONTEND_DASHBOARD}/:${PORT_FRONTEND_DASHBOARD}/g" ${TARGET_FILE}

exec nginx -g 'daemon off;'